// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 2017.05.1-antlia
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#include "../inc/accelerometer.hpp"



accelerometer::accelerometer() :
    analog_clock_old(false),
    avx_old(0.0),
    avy_old(0.0),
    avz_old(0.0),
    hif_a2t_data(
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    false),
    accelerometer_V_Cap7(0.0),
    accelerometer_V_Cap5(0.0),
    accelerometer_V_Cap2(0.0),
    accelerometer_V_Cap1(0.0),
    accelerometer_V_avz_dot(0.0),
    accelerometer_V_avy_dot(0.0),
    accelerometer_V_avx_dot(0.0),
    accelerometer_V_reduced_1_dot(0.0),
    accelerometer_V_reduced_0_dot(0.0),
    accelerometer_V_reduced_1(0.0),
    accelerometer_V_avy(0.0),
    accelerometer_V_avz(0.0),
    accelerometer_V_avx(0.0),
    accelerometer_V_reduced_0(0.0),
    process_in_queue(false),
    flag_analog_clock(false)
{
}


accelerometer::~accelerometer()
{}


void accelerometer::process()
{

    // Set input values.
    accelerometer_V_avx = hif_a2t_data.avx;

    // Set input values.
    accelerometer_V_avy = hif_a2t_data.avy;

    // Set input values.
    accelerometer_V_avz = hif_a2t_data.avz;
    accelerometer_V_reduced_0 = hif_a2t_data.accelerometer_V_avx_ddt * 0.00372814
         + hif_a2t_data.accelerometer_V_avy_ddt * 2.11504 + hif_a2t_data.accelerometer_V_avz_ddt
         * -5.33633e-05 + hif_a2t_data.accelerometer_V_reduced_0_ddt * 0.612305
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 12.2461 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * 6.30319e-15 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 1.26064e-13
         + accelerometer_V_avx * -0.00372814 + accelerometer_V_avy * -2.11504 +
         accelerometer_V_avz * 5.33633e-05;
    accelerometer_V_reduced_1 = hif_a2t_data.accelerometer_V_avx_ddt * 2.13393 +
         hif_a2t_data.accelerometer_V_avy_ddt * -0.00369513 + hif_a2t_data.accelerometer_V_avz_ddt
         * -0.0305444 + hif_a2t_data.accelerometer_V_reduced_0_ddt * 5.91755e-15
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 1.69743e-13 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * 0.612305 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 12.2461 +
         accelerometer_V_avx * -2.13393 + accelerometer_V_avy * 0.00369513 + accelerometer_V_avz
         * 0.0305444;
    accelerometer_V_reduced_0_dot = hif_a2t_data.accelerometer_V_avx_ddt * 0.000186407
         + hif_a2t_data.accelerometer_V_avy_ddt * 0.105752 + hif_a2t_data.accelerometer_V_avz_ddt
         * -2.66817e-06 + hif_a2t_data.accelerometer_V_reduced_0_ddt * -0.0193847
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 0.612305 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * 3.1516e-16 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 6.30319e-15
         + accelerometer_V_avx * -0.000186407 + accelerometer_V_avy * -0.105752
         + accelerometer_V_avz * 2.66817e-06;
    accelerometer_V_reduced_1_dot = hif_a2t_data.accelerometer_V_avx_ddt * 0.106697
         + hif_a2t_data.accelerometer_V_avy_ddt * -0.000184756 + hif_a2t_data.accelerometer_V_avz_ddt
         * -0.00152722 + hif_a2t_data.accelerometer_V_reduced_0_ddt * 4.10488e-16
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 5.25424e-15 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * -0.0193847 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 0.612305
         + accelerometer_V_avx * -0.106697 + accelerometer_V_avy * 0.000184756 +
         accelerometer_V_avz * 0.00152722;
    accelerometer_V_avx_dot = hif_a2t_data.accelerometer_V_avx_ddt * -0.05 + accelerometer_V_avx
         * 0.05;
    accelerometer_V_avy_dot = hif_a2t_data.accelerometer_V_avy_ddt * -0.05 + accelerometer_V_avy
         * 0.05;
    accelerometer_V_avz_dot = hif_a2t_data.accelerometer_V_avz_ddt * -0.05 + accelerometer_V_avz
         * 0.05;
    accelerometer_V_Cap1 = hif_a2t_data.accelerometer_V_avx_ddt * 1.28512e-13 +
         hif_a2t_data.accelerometer_V_avy_ddt * 4.31727e-15 + hif_a2t_data.accelerometer_V_avz_ddt
         * -1.83947e-15 + hif_a2t_data.accelerometer_V_reduced_0_ddt * 1.31427e-15
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 2.62854e-14 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * 3.68725e-14 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 7.3745e-13
         + accelerometer_V_avx * -1.28512e-13 + accelerometer_V_avy * -4.31727e-15
         + accelerometer_V_avz * 1.83947e-15 - 3.20699e-13;
    accelerometer_V_Cap2 = hif_a2t_data.accelerometer_V_avx_ddt * 4.31725e-15 +
         hif_a2t_data.accelerometer_V_avy_ddt * -1.28512e-13 + hif_a2t_data.accelerometer_V_avz_ddt
         * -6.17956e-17 + hif_a2t_data.accelerometer_V_reduced_0_ddt * -3.72019e-14
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * -7.44038e-13 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * 1.30377e-15 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * 2.60755e-14
         + accelerometer_V_avx * -4.31725e-15 + accelerometer_V_avy * 1.28512e-13
         + accelerometer_V_avz * 6.17956e-17 - 3.20699e-13;
    accelerometer_V_Cap5 = hif_a2t_data.accelerometer_V_avx_ddt * -1.28513e-13 +
         hif_a2t_data.accelerometer_V_avy_ddt * -4.31725e-15 + hif_a2t_data.accelerometer_V_avz_ddt
         * 1.8395e-15 + hif_a2t_data.accelerometer_V_reduced_0_ddt * -1.31427e-15
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * -2.62853e-14 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * -3.6873e-14 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * -7.3746e-13
         + accelerometer_V_avx * 1.28513e-13 + accelerometer_V_avy * 4.31725e-15
         + accelerometer_V_avz * -1.8395e-15 + 3.20699e-13;
    accelerometer_V_Cap7 = hif_a2t_data.accelerometer_V_avx_ddt * -4.31727e-15 +
         hif_a2t_data.accelerometer_V_avy_ddt * 1.28513e-13 + hif_a2t_data.accelerometer_V_avz_ddt
         * 6.17958e-17 + hif_a2t_data.accelerometer_V_reduced_0_ddt * 3.72024e-14
         + hif_a2t_data.accelerometer_V_reduced_0_dot_ddt * 7.44048e-13 + hif_a2t_data.accelerometer_V_reduced_1_ddt
         * -1.30378e-15 + hif_a2t_data.accelerometer_V_reduced_1_dot_ddt * -2.60756e-14
         + accelerometer_V_avx * 4.31727e-15 + accelerometer_V_avy * -1.28513e-13
         + accelerometer_V_avz * -6.17958e-17 + 3.20699e-13;

    // Update discretization variables.
    hif_a2t_data.accelerometer_V_avx_ddt = accelerometer_V_avx;
    hif_a2t_data.accelerometer_V_avy_ddt = accelerometer_V_avy;
    hif_a2t_data.accelerometer_V_avz_ddt = accelerometer_V_avz;
    hif_a2t_data.accelerometer_V_reduced_0_ddt = accelerometer_V_reduced_0;
    hif_a2t_data.accelerometer_V_reduced_0_dot_ddt = accelerometer_V_reduced_0_dot;
    hif_a2t_data.accelerometer_V_reduced_1_ddt = accelerometer_V_reduced_1;
    hif_a2t_data.accelerometer_V_reduced_1_dot_ddt = accelerometer_V_reduced_1_dot;

    // Set output values.
    hif_a2t_data.Cap7 = accelerometer_V_Cap7;

    // Set output values.
    hif_a2t_data.Cap5 = accelerometer_V_Cap5;

    // Set output values.
    hif_a2t_data.Cap2 = accelerometer_V_Cap2;

    // Set output values.
    hif_a2t_data.Cap1 = accelerometer_V_Cap1;
}


void accelerometer::update_input_queue( bool synch_phase )
{
    process_in_queue = false;
    avz_old = hif_a2t_data.avz;
    avy_old = hif_a2t_data.avy;
    avx_old = hif_a2t_data.avx;
    if (hif_a2t_data.analog_clock != analog_clock_old)
    {
        analog_clock_old = hif_a2t_data.analog_clock;
        flag_analog_clock = true;
        process_in_queue = true;
    }
    else
    {
        flag_analog_clock = false;
    }
}


void accelerometer::update_event_queue()
{
    process_in_queue = false;
}


void accelerometer::flag_elaboration()
{
    if (flag_analog_clock)
    {
        process();
    }
}


void accelerometer::synch_elaboration()
{
    update_input_queue( true );
    flag_elaboration();
    flag_analog_clock = false;
    update_event_queue();
}


void accelerometer::simulate( accelerometer_iostruct * io_exchange, int32_t & cycles_number
     )
{
    hif_a2t_data.avz = io_exchange->avz;
    hif_a2t_data.avy = io_exchange->avy;
    hif_a2t_data.avx = io_exchange->avx;
    hif_a2t_data.analog_clock = io_exchange->analog_clock;
    cycles_number = cycles_number + 1L;
    synch_elaboration();
    while (process_in_queue)
    {
        flag_elaboration();
        update_event_queue();
    }
    io_exchange->accelerometer_V_reduced_0_dot_ddt = hif_a2t_data.accelerometer_V_reduced_0_dot_ddt;
    io_exchange->accelerometer_V_avx_ddt = hif_a2t_data.accelerometer_V_avx_ddt;
    io_exchange->accelerometer_V_avy_ddt = hif_a2t_data.accelerometer_V_avy_ddt;
    io_exchange->accelerometer_V_avz_ddt = hif_a2t_data.accelerometer_V_avz_ddt;
    io_exchange->accelerometer_V_reduced_1_dot_ddt = hif_a2t_data.accelerometer_V_reduced_1_dot_ddt;
    io_exchange->accelerometer_V_reduced_1_ddt = hif_a2t_data.accelerometer_V_reduced_1_ddt;
    io_exchange->accelerometer_V_reduced_0_ddt = hif_a2t_data.accelerometer_V_reduced_0_ddt;
    io_exchange->Cap7 = hif_a2t_data.Cap7;
    io_exchange->Cap5 = hif_a2t_data.Cap5;
    io_exchange->Cap2 = hif_a2t_data.Cap2;
    io_exchange->Cap1 = hif_a2t_data.Cap1;
}


void accelerometer::start_of_simulation()
{
    process();
    update_event_queue();
}


void accelerometer::initialize()
{
    start_of_simulation();
}


void accelerometer::finalize()
{
}




